image: php:8.0

stages:
  - deploy

cache:
  paths:
    - vendor/

deploy:
  stage: deploy
  only:
    - master
  rollback:
    enabled: true
    branch: master
    message: "Deployment failed, rolling back to previous version."
  script:
    - apt-get update && apt-get install -y sshpass
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER_NAME@$SSH_HOST "cd ../../var/www/DEMOCICD && sudo git pull"