name: php-ci

on:
  pull_request:
    branches: [ "master" ]
    types: [ closed ]
jobs:
  deploy:
    name: build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - name: Deploy code
      run: |
        ssh -o "StrictHostKeyChecking no" user@server "cd ../../democicd/ && git pull && composer install && php artisan migrate --force"